export const PERMISSIONS = {
  // Modules
  MOD_DASHBOARD: 'MOD_DASHBOARD',
  MOD_PATIENTS: 'MOD_PATIENTS',
  MOD_APPOINTMENTS: 'MOD_APPOINTMENTS',
  MOD_TRIAGE: 'MOD_TRIAGE',
  MOD_CONSULTATION: 'MOD_CONSULTATION',
  MOD_LAB: 'MOD_LAB',
  MOD_BILLING: 'MOD_BILLING',
  MOD_ADMIN: 'MOD_ADMIN',

  // Actions (Generic)
  ACT_VIEW: 'ACT_VIEW',
  ACT_CREATE: 'ACT_CREATE',
  ACT_EDIT: 'ACT_EDIT',
  ACT_DELETE: 'ACT_DELETE',

  // Specifics
  CMP_PATIENT_ADD: 'CMP_PATIENT_ADD',
  CMP_PATIENT_LIST: 'CMP_PATIENT_LIST',
  CMP_PATIENT_VIEW: 'CMP_PATIENT_VIEW',
  CMP_PATIENT_EDIT: 'CMP_PATIENT_EDIT',
  CMP_APPOINTMENT_LIST: 'CMP_APPOINTMENT_LIST',
  CMP_APPOINTMENT_CREATE: 'CMP_APPOINTMENT_CREATE',
  CMP_APPOINTMENT_VIEW: 'CMP_APPOINTMENT_VIEW',
  CMP_APPOINTMENT_EDIT: 'CMP_APPOINTMENT_EDIT',
  CMP_LAB_ENTRY: 'CMP_LAB_ENTRY',
};
