export const PERMISSIONS = {
  // Modules
  MOD_DASHBOARD: 'MOD_DASHBOARD',
  MOD_PATIENTS: 'MOD_PATIENTS',
  MOD_APPOINTMENTS: 'MOD_APPOINTMENTS',
  MOD_TRIAGE: 'MOD_TRIAGE',
  MOD_CONSULTATION: 'MOD_CONSULTATION',
  MOD_LAB: 'MOD_LAB',
  MOD_BILLING: 'MOD_BILLING',
  MOD_ADMIN: 'MOD_ADMIN',

  // Actions
  ACT_VIEW: 'ACT_VIEW',
  ACT_CREATE: 'ACT_CREATE',
  ACT_EDIT: 'ACT_EDIT',
  ACT_DELETE: 'ACT_DELETE',

  // Components / Features
  CMP_VITALS_WRITE: 'CMP_VITALS_WRITE',
  CMP_VITALS_READ: 'CMP_VITALS_READ',
  CMP_PATIENT_ADD: 'CMP_PATIENT_ADD',
  CMP_PATIENT_LIST: 'CMP_PATIENT_LIST',
  CMP_PATIENT_VIEW: 'CMP_PATIENT_VIEW',
  CMP_PATIENT_EDIT: 'CMP_PATIENT_EDIT',

  CMP_APPOINTMENT_LIST: 'CMP_APPOINTMENT_LIST',
  CMP_APPOINTMENT_CREATE: 'CMP_APPOINTMENT_CREATE',
  CMP_APPOINTMENT_VIEW: 'CMP_APPOINTMENT_VIEW',
  CMP_APPOINTMENT_EDIT: 'CMP_APPOINTMENT_EDIT',

  CMP_CONSULTATION_READ: 'CMP_CONSULTATION_READ',
  CMP_CONSULTATION_WRITE: 'CMP_CONSULTATION_WRITE',

  CMP_LAB_ENTRY: 'CMP_LAB_ENTRY',
  CMP_LAB_READ: 'CMP_LAB_READ',

  CMP_INVOICE_GENERATE: 'CMP_INVOICE_GENERATE',
  CMP_PAYMENT_RECEIPT: 'CMP_PAYMENT_RECEIPT',
  CMP_BILLING_SUMMARY: 'CMP_BILLING_SUMMARY',

  CMP_ADMIN_DEPT_READ: 'CMP_ADMIN_DEPT_READ',
  CMP_ADMIN_DEPT_WRITE: 'CMP_ADMIN_DEPT_WRITE',
  CMP_ADMIN_USER_READ: 'CMP_ADMIN_USER_READ',
  CMP_ADMIN_USER_WRITE: 'CMP_ADMIN_USER_WRITE',
  CMP_ADMIN_ROLE_WRITE: 'CMP_ADMIN_ROLE_WRITE',
};
