import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { MessageService } from 'primeng/api';
import {
  LabService,
  LabRequest,
  LabTest,
} from '../../../../core/services/lab.service';
import { PatientService } from '../../../../core/services/patient.service';
import { Patient } from '../../../../core/models/patient.model';

@Component({
  selector: 'app-test-request',
  templateUrl: './test-request.component.html',
  styleUrl: './test-request.component.scss',
})
export class TestRequestComponent implements OnInit {
  patients: Patient[] = [];
  tests: LabTest[] = [];
  priorities: any[] = [
    { label: 'Routine', value: 'ROUTINE' },
    { label: 'Urgent', value: 'URGENT' },
    { label: 'Emergency', value: 'EMERGENCY' },
  ];

  selectedPatient: Patient | null = null;
  selectedTest: LabTest | null = null;
  priority: 'ROUTINE' | 'URGENT' | 'EMERGENCY' = 'ROUTINE';
  doctorName: string = '';
  notes: string = '';

  loading = false;
  submitted = false;

  constructor(
    private labService: LabService,
    private patientService: PatientService,
    private messageService: MessageService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.patientService
      .getPatients()
      .subscribe((data) => (this.patients = data));
    this.labService.getTests().subscribe((data) => (this.tests = data));
  }

  save() {
    this.submitted = true;
    if (this.selectedPatient && this.selectedTest && this.doctorName) {
      this.loading = true;

      const request: LabRequest = {
        id: 0, // Generated by service
        patientId: this.selectedPatient.id,
        patientName: this.selectedPatient.name,
        doctorName: this.doctorName,
        testName: this.selectedTest.name,
        requestDate: new Date(),
        status: 'Pending',
        priority: this.priority,
        technicianNotes: this.notes,
      };

      this.labService.createRequest(request).subscribe(() => {
        this.messageService.add({
          severity: 'success',
          summary: 'Success',
          detail: 'Test Requested',
        });
        this.router.navigate(['/lab']);
      });
    }
  }

  cancel() {
    this.router.navigate(['/lab']);
  }
}
